language: c
sudo: required
dist: trusty
compiler:
   - gcc
   - clang
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y build-essential automake libsdl2-dev libsdl2-image-dev libgl1-mesa-dev libxml2-dev libfreetype6-dev libpng12-dev libopenal-dev libvorbis-dev binutils-dev libzip-dev libiberty-dev libluajit-5.1-dev luarocks
   - sudo luarocks install ldoc
script:
   - "./autogen.sh && ./configure && make"
   - cd docs && ./luadoc.sh && cd ..
